### ISSUE TITLE
[regression] Inconsistent results on travis-ci

### ISSUE THREAD

**Issue by nemesisdesign** [timothycrosley/isort#541] opened 2017-06-01 10:46 UTC
After the last release I started to get [inconsistent results on travis](https://travis-ci.org/openwisp/django-netjsonconfig/jobs/238291068) again (python3).

I cannot replicate and fix the issues.

I opened this issue even though I don't have much details to offer, hoping that if more people are experiencing the same problem they will help to debug, for now I will try to pin the test requirements to the previous stable version.

**Comment by samuelcolvin** [comment] 2017-06-01 11:30
I'm getting this too, it's not the same as #457. Which I think was caused by installing some packages locally.

Example: https://travis-ci.org/samuelcolvin/arq/jobs/238303765

**Comment by timothycrosley** [comment] 2017-06-01 15:28
@nemesisdesign: Do you mean inconsistent from local running of isort? I couldn't reproduce this issue, but I did notice you only run isort for Python3 - so it couldn't be inconsistencies between Python versions. It looks like on travis it's incorrectly identifying a project level import, is this correct?

Thanks!

~Timothy

**Comment by krzysztof** [comment] 2017-06-02 13:26
I don't think it was a case for @nemesisdesign build, but in general you might get inconsistencies if travis is caching pip and using cached isort in version other than your local one.

**Comment by samuelcolvin** [comment] 2017-06-04 14:19
another example: https://travis-ci.org/em-2/em2/jobs/239309361

pytest-isort on travis wants blank lines but pytest-isort locally doesn't care. This is fixed by running `isort` itself locally which adds the new lines

**Comment by nemesisdesign** [comment] 2017-06-05 16:48
@krzysztof thank you for the tip. I've ran into the same issue before and it was a pain to fix. But this time I tried the same fix I applied last time and it didn't work.

I worked around it by pinning isort to 4.2.5 for the moment.

**Comment by nemesisdesign** [comment] 2017-06-06 10:51
@timothycrosley in short, the problem is that I cannot get the same output of the travis build in my local development environment, I'm having this issues in several python packages.

I usually create my virtualenvs with the following command:

```shell
mkvirtualenv --python=/usr/bin/python3 <name>
```

May it be a problem with virtualenvwrapper? I really don't know :-/

**Comment by nemesisdesign** [comment] 2017-06-06 10:56
Or maybe is a misunderstanding in how the library should be used? Not sure!

**Comment by krzysztof** [comment] 2017-06-06 12:30
@nemesisdesign It looks like a problem with the isort distinction between first/third party packages, when they are installed from dev dependencies. Try creating an .editorconfig file and setting "known_third_party" value, which specifies the dependencies for some of the requirements you have here: https://github.com/openwisp/django-netjsonconfig/blob/master/requirements.txt

For example, our editorconfig:
https://github.com/inveniosoftware/invenio-records/blob/master/.editorconfig#L40
Libraries we install from as dev dependencies:
https://github.com/inveniosoftware/invenio-records/blob/master/requirements-devel.txt

**Comment by sobolevn** [comment] 2017-06-09 11:45
@krzysztof You are my hero of the day. Solved my inconsistent test results with:

```
[*.py]
known_first_party = split_settings
default_section = THIRDPARTY
```

**Comment by nemesisdesign** [comment] 2017-06-21 15:21
@krzysztof @timothycrosley:
I tried updating to the latest version (4.2.15) and the build on travis now only complains about missing blank lines:
https://travis-ci.org/netjson/django-netjsongraph/jobs/245409125

**Comment by nemesisdesign** [comment] 2017-06-21 15:36
I solved that build issue by specifying `known_first_party` and `default_section` as suggested:
https://github.com/netjson/django-netjsongraph/commit/3f29fdb7a5a075232513edca627246a6f3312269

It's a shame I will have to do this for all my projects though.. there are quite a few [openwisp2](https://github.com/openwisp/ansible-openwisp2) modules out there I will need to upgrade..

**Comment by jleclanche** [comment] 2017-09-02 14:44
I had the same issue as described above, despite already having `known_third_party = mylib`. Had to add `default_section = THIRDPARTY` as well to get consistent results, I don't really understand why that's needed.

**Comment by timothycrosley** [comment] 2019-03-10 07:00
I've done a significant amount of work to improve consistency across environments and platforms in the last few releases, i hope I have resolved these issues and am therefore closing this report. If I closed incorrectly please comment to let me know!

Thanks!

~Timothy

**Closed by timothycrosley** 2019-03-10 07:00 UTC
Labels: bug

**Comment by samuelcolvin** [comment] 2019-03-11 10:32
Thanks Timothy, I use isort on almost all my projects and it's now extremely consistent across different platforms.
