### ISSUE TITLE
Import as mucks with alphabetical sorting

### ISSUE THREAD

**Issue by Rotonen** [timothycrosley/isort#590] opened 2017-08-25 15:18 UTC
A `poc.py` file:

```
from os import defpath
from os import pathsep as separator
```

Wants to sort (without a config file):

```
isort --diff poc.py
--- /Users/joni/koodaus/git/isort/poc.py:before	2017-08-25 17:17:11
+++ /Users/joni/koodaus/git/isort/poc.py:after	2017-08-25 17:17:13.781499
@@ -1,2 +1,2 @@
+from os import pathsep as separator
 from os import defpath
-from os import pathsep as separator
```

It seems it'd consider the as import to alphabetize as 'as'.

Is this a bug or is this somehow a misconfiguration or a user error?

**Comment by timothycrosley** [comment] 2017-08-29 02:16
Hi @Rotonen,

Thanks for reporting this issue! Unfortunately, with the information given, I was unable to reproduce this issue - as shown by the test case added here: https://github.com/timothycrosley/isort/pull/591/files. Can you provide any more information, such as the version of isort, your OS, as well as double check that you do not have any project or global level isort configs?

Thanks!

~Timothy

**Comment by Rotonen** [comment] 2017-08-29 02:28
I'm testing with Python 3.6.2 and isort 4.2.15 on macOS 10.12.6. Python is installed via pyenv.

I have no `~/.isort.cfg` nor a local `setup.cfg`. The directory of the poc.py is otherwise empty.

https://github.com/timothycrosley/isort/blob/01df61383cf1d85a3b912ce501532ff15cbd1bd9/isort/settings.py#L139

Based on this, I should not currently have a config file at all for isort as far as I understand how this ticks.

**Comment by Rotonen** [comment] 2017-08-29 02:32
```
env | grep LC
LC_ALL=
LC_MONETARY=de_CH.UTF-8
LC_COLLATE=fi_FI.UTF-8
LC_CTYPE=fi_FI.UTF-8
LC_NUMERIC=fi_FI.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_TIME=fi_FI.UTF-8
```

Here is also the `LC_*` from my env in case collation or somesuch underlying layer of functionality might play into this.

**Comment by timothycrosley** [comment] 2017-08-29 02:41
Thanks @Rotonen, this information is extremely helpful, your assumptions of how it works is correct. I'll take a look at it once I'm home using the exact information you've provided and update this ticket accordingly.

Thanks again!

~Timothy

**Comment by Rotonen** [comment] 2017-08-29 02:50
FWIW does not seem to be a collation issue either:

```
LC_ALL=C isort --diff poc.py
--- /Users/rotonen/temp/isort/poc.py:before	2017-08-29 04:22:17
+++ /Users/rotonen/temp/isort/poc.py:after	2017-08-29 04:41:03.489338
@@ -1,2 +1,2 @@
+from os import pathsep as separator
 from os import defpath
-from os import pathsep as separator
```

Reproduction steps:
1. Install pyenv
2. Install pyenv-virtualenv
3. `pyenv install 3.6.2`
4. `pyenv virtualenv 3.6.2 isort`
5. Create a directory for the PoC
6. Create `poc.py`
7. `pyenv local 3.6.2/envs/isort`
8. `pip install isort`
9. `isort --diff poc.py`

With these steps I've now also replicated the behaviour for me on Debian 8.9.

**Comment by timothycrosley** [comment] 2017-08-29 06:39
I've been able to reproduce this issue and can verify its status as a bug. The issue was with my test case and not with your issue report, A fix for the issue will make its way into the next point release, with a test case added to catch similar issues in the future.

Thanks!

~Timothy

**Comment by timothycrosley** [comment] 2017-08-31 08:23
Thanks for reporting this issue!

This is now fixed in develop and will work correctly in the next release.

Luckily this was not as broad as it initially seemed, it only affects from imports where there is a mix of blanket `from module import variable` and `from module import variable2 as variable1` where `module` is the same, and `combine_as_imports` is set to `False` (the default) forcing them to be on the same line. This situation always adds some ambiguity, even now that it is improved, IE now it will do:

```python
    from module import a, b
    from module import c as c_1
    from module import d
```

Where as before it would render as:

```python
    from module import c as c_1
    from module import a, b, d
```
Which some might not like as it increases the number of lines, but I think it is strictly speaking much more correct.

Thanks!

~Timothy

**Closed** 2017-08-31 08:23 UTC
Labels: bug
