### ISSUE TITLE
Need way to enforce everything but the wrapping style

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#380] opened 2015-12-17 14:49 UTC
We're running isort on Travis, since we want to enforce import order (and avoid dupes etc). 
However, there isn't a way to enforce this without also imposing a wrapping style.

This is problematic for us, since it's quite hard to pick a wrapping mode that's both pretty/what we want, and also deterministic for a human that might not be familiar with our isort config and exact max line length etc. (We don't enforce a max line length in our codebase, we leave that up to best judgement).

For example, the "prettiest" style for me would probably be:

```
[isort]
multi_line_output = 0
force_grid_wrap = false
line_length = 100
```

eg:

``` python
from third_party import lib1, lib2, lib3, lib4, lib5
from another_third_party import (lib1, lib2, lib3, ...
                                 libX, libY, ...)
```

However the user then has to keep a close eye on the line length and can't make a judgement call - since they'll then get bitten by the Travis run when pushing to GitHub.

An "easier to guess when writing code" style (and what we're using for now) is:

```
[isort]
multi_line_output = 1
force_grid_wrap = true
line_length = 140
```

However this results in multi-line imports when not really necessary:

eg:

``` python
from third_party import (lib1,
                         lib2)
```

It would be great if we could enforce only the order of imports (and that there aren't dupes etc) and not the wrapping style, to avoid these issues.

**Comment by mverteuil** [comment] 2016-01-27 19:41
Thanks so much for mentioning `force_grid_wrap` here, as it's missing from the documentation. I never would have been able to solve my problem if I hadn't see this.  Kudos @edmorley, I hope your problem is resolved!

**Comment by edmorley** [comment] 2016-01-29 23:35
You're welcome :-)

I've just added `force_grid_wrap` to the wiki page here:
https://github.com/timothycrosley/isort/wiki/isort-Settings/_compare/b3a74962de5e0837e2d96960454d3b3b32a65be4...ff0beb6b800f88cba5050ffe621ad056ab4a0ddf

**Comment by timothycrosley** [comment] 2016-03-27 04:50
@edmorley, I agree and I would be more then willing to accept a pull-request that implements this. The problem is isort was never built to check import order, it was built to re-order. The checking was an after thought. This matters because checking is implemented simply by running isort with a specified config and then diffing the isorted against the non-isorted. As I'm sure you can see this makes that style of checking simply not possible without a very large refactoring effort, which I do not have the time to undertake right now, but would be very happy to see done :)

**Comment by edmorley** [comment] 2016-03-31 09:51
Yeah totally understand this would be a substantial change in approach/rewrite. Maybe one day I'll have a spare moment to take a look :-)

**Comment by timothycrosley** [comment] 2020-07-16 06:27
Since it's been many years and no other users have requested this I'm going to close the issue, but I'm still open to PRs that add support for this, and I'm hopeful that one of the newer wrap modes solved your issue.

Thanks!

~Timothy

**Closed by timothycrosley** 2020-07-16 06:27 UTC
Labels: enhancement
