### ISSUE TITLE
isort behavior different on linux vs osx

### ISSUE THREAD

**Issue by ahonnecke** [timothycrosley/isort#722] opened 2018-07-17 18:12 UTC
OSX:
```bash
pipenv run isort server/portfolio_manager/management/commands/safe_migrate.py
```

```python
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

from db_mutex import DBMutexError, DBMutexTimeoutError
from db_mutex.db_mutex import db_mutex
```

Ubuntu 16.04:
```bash
pipenv run isort server/portfolio_manager/management/commands/safe_migrate.py
```

```python
from db_mutex import DBMutexError, DBMutexTimeoutError
from db_mutex.db_mutex import db_mutex
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError
```

Perhaps there is a setting that would force OSX to behave like ubuntu that I'm missing?

**Comment by ahonnecke** [comment] 2018-07-17 20:02
I resolved it with 
```
[settings]
known_django=django
sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```

Still seems like the defaults should work on both platforms.

**Comment by scorphus** [comment] 2018-09-11 14:55
This is a duplicate of #725. Can you please close it?

**Closed** 2018-12-19 17:57 UTC
