### ISSUE TITLE
Doesn't recognize `async def`

### ISSUE THREAD

**Issue by vad** [timothycrosley/isort#537] opened 2017-05-31 12:02 UTC
In the following code:

```py
from myapp import myfunction

 
async def test_myfunction(test_client, app):
    a = await myfunction(test_client, app)
```

`isort` (4.2.5) tries to remove a newline. Are `async def` recognized by isort?

**Comment by timothycrosley** [comment] 2017-06-01 06:40
This is fixed in the just released to PYPI `4.2.8` release.

Thanks!

~Timothy

**Closed by timothycrosley** 2017-06-01 06:40 UTC

**Comment by vad** [comment] 2017-06-01 07:08
:+1: it works, thank you!

**Comment by meisenberg** [comment] 2017-06-14 00:25
This is broken again in isort 4.2.15.

**Comment by timothycrosley** [comment] 2017-06-14 04:57
@meisenberg I've added an additional test case with the exact usage asked about in this issue, and it passes against 4.2.15 - what is the exact case you are running into, as this is indeed fixed in 4.2.15?

Thanks!

~Timothy

**Comment by meisenberg** [comment] 2017-06-14 21:36
Apologies, I can't reproduce now; I must have had a different version of the package installed than I thought.
