### ISSUE TITLE
future imports and 'isort:skip' don't work together

### ISSUE THREAD

**Issue by spookylukey** [timothycrosley/isort#488] opened 2016-12-16 17:14 UTC
For example:

    from __future__ import absolute_import
    
    import foo # isort:skip
    
    import os

`isort -c` on this file incorrectly says "Imports are incorrectly sorted". If the `__future__` imports are removed, there is no error. Putting "import foo" above the future import works, but is a problem in other ways (e.g. now flake8 rightly complains).

**Comment by Hnasar** [comment] 2019-08-21 22:30
Duplicate of #455

**Comment by timothycrosley** [comment] 2020-01-05 10:48
Closing due to duplication

**Closed by timothycrosley** 2020-01-05 10:48 UTC
Labels: enhancement
