### ISSUE TITLE
check_stream does not respect the quiet flag

### ISSUE THREAD

**Issue by quoimec** [timothycrosley/isort#1369] opened 2020-08-05 04:04 UTC
Pretty simple request, in line 216 of isort/api.py there is a printer.error statement that always fires, irrespective of if the quiet flag has been set as a config argument.

**Comment by quoimec** [comment] 2020-08-05 04:11
Opened PR: https://github.com/timothycrosley/isort/pull/1370

**Comment by timothycrosley** [comment] 2020-08-05 04:12
Hi @quoimec,

Thanks for forwarding your feedback! And putting together a PR!

Can you help me understand what it is you are trying to accomplish that this is blocking you from being able to?

The current documentation says the quiet option should
`Shows extra quiet output, only errors are outputted.`. And in fact, what it is that you don't want to be outputed is the error it talks about. I'm trying to understand, quiet or not, why check would be used without wanting the errors to be outputted.

Thanks!

~Timothy

**Comment by quoimec** [comment] 2020-08-05 04:25
Hello! 

So on my end what I am aiming to accomplish is the ability to run isort, count the number of files changed and then display that information to a user. 

I'm using the sort_file method to make the changes but as far as I can see, there is no output from that operation to check if the file has actually changed. My approach was to make a call to check_file beforehand and record if there are changes that need to be made, but then this obviously throws up an error message every time, hence the issue.

I had missed that point in the documentation re: error printing and I think it definitely makes sense but in saying that, I'm not exactly sure if the check method confirming that a file needs to be changed counts as an error? Is check_stream used elsewhere in the package for the purposes of flagging an error? 

Super happy to use a different approach if you have one and if this is too much hassle for you, no worries at all hahaha - counting file changes is not mission critical to what I am building, definitely falls into the nice to have bucket.

Cheers!

Charlie

**Comment by timothycrosley** [comment] 2020-08-05 04:41
Hi Charlie!

Thanks for providing the additional background information! How would you feel if the `sort_file` method started returning a boolean value to indicate whether or not the given file had changed? This would make it more in-line with other API methods.

My main concern with changing the behaviour of the `--quiet` flag, is just because of the number of users of isort, it's hard to know for sure what unexpected behaviour people might depend on, so I try to minimize these kind of changes to major releases, and another one isn't expected for a year at least. 

Thanks!

~Timothy

**Comment by quoimec** [comment] 2020-08-05 05:12
Yeah totally understandable and that would be fantastic - I'll make the changes and send up another PR shortly!

**Comment by timothycrosley** [comment] 2020-08-05 05:14
@quoimec I may have been too quick to act! I would have happily accepted your PR, however I did make one already here: https://github.com/timothycrosley/isort/commit/79bad69f55d50ab35712ca7f01feefddccfe1add.

That said, I did not write a test for it! If you would be willing to make a PR that adds a test case, that would be really appreciated.

Thanks!

~Timothy

**Comment by quoimec** [comment] 2020-08-05 05:31
All good! I'll have a look when I get a chance tonight. Thank you for all of your prompt help on this.

**Comment by timothycrosley** [comment] 2020-08-05 05:35
Always happy to help!

**Comment by timothycrosley** [comment] 2020-08-07 07:17
Closing as the API improvements have landed in the 5.3.0 release

**Closed by timothycrosley** 2020-08-07 07:17 UTC
Labels: documentation, idea_for_next_major_release, question
