### ISSUE TITLE
Inconsistent output from same version

### ISSUE THREAD

**Issue by danielsamuels** [timothycrosley/isort#379] opened 2015-12-16 20:35 UTC
I'm currently testing the use of `isort` in a test project [here](https://github.com/onespacemedia/test-cms-project/blob/eca99e5da2cb5f06ea6d226c119bc3577212d9dd/.travis.yml#L8). When run through Travis-CI I get a successful exit, with [no errors](https://travis-ci.org/onespacemedia/test-cms-project/builds/97305886). But when using the same version locally, I get errors:

![](https://i.imgur.com/V3qsegm.png) (Text available as a [gist](https://gist.github.com/danielsamuels/ca77614d2018424abc57).)

Any idea why the same version would give different results?

**Comment by hobarrera** [comment] 2016-02-08 22:37
I'm having a very similar scenario, running via tox displays errors, while running manually does not (or viceversa, depending on how I adapt my code, of course):

    isort --recursive --diff --check-only --multi_line 2 --combine-as --skip-glob migrations --project idf idf

It also looks like the same error because the problem is also that my first-party modules are being mixed up with third party modules.

**Comment by hobarrera** [comment] 2016-02-08 22:50
I found out that in my case, this is related to third-party modules not being detected properly - rather than what I though, that first-party modules were not being detected properly.

If I explicitly list all my third party libs, then running via `tox` gives the expected output. Maybe you're having the same issue on your case, @danielsamuels?

**Comment by danielsamuels** [comment] 2016-02-08 22:52
Perhaps. I just run a bare `isort` command at the moment, so I may need to be a little more explicit. I'll have a play with it.

**Comment by danielsamuels** [comment] 2016-02-08 22:53
Perhaps not exactly a 'bare' command actually, this is what I'm currently using:

```
isort --check-only --diff --quiet --skip-glob=.venv --skip-glob=node_modules --skip-glob=*/migrations/*
```

**Comment by hobarrera** [comment] 2016-02-09 01:11
I recommend that you try adding `-o KNOWN_THIRD_PARTY, --thirdparty KNOWN_THIRD_PARTY` option and see if the issue persists. If it does not, then you're just suffering from the above linked issue.

(note: I'm not an isort developer, just a user who came across a similar scenario, possibly the same).

**Comment by nemesisdesign** [comment] 2016-02-17 15:07
I am also experiencing this issue, although it could also be a travis-ci issue. Not sure.

**Comment by ppolewicz** [comment] 2016-03-05 14:50
I am hitting the same issue with running isort locally and running it with Travis-CI. My command is:
`isort --order-by-type --recursive --line-width 100 --diff --verbose --check-only`
When run on Travis-CI, it correctly splits modules of our "whylog" project from other imports, but when run locally, it is not split:

```
 from generator import generate, generator
 from nose.plugins.skip import SkipTest
-
 from whylog.client import WhylogClient
 from whylog.config import YamlConfig
```
So running `isort` locally before committing actually breaks sorting (and then Travis detects an error).

Correct me if I'm wrong, but this doesn't seem to be related to third party.

**Comment by hobarrera** [comment] 2016-03-05 16:17
> Correct me if I'm wrong, but this doesn't seem to be related to third party.

Have you tried being explicit about third-party libs and making sure? It does sound like the same issue I'm having.

**Comment by hobarrera** [comment] 2016-03-06 10:22
@bd4e5f6 fixes this issue, at least for me.

**Comment by timothycrosley** [comment] 2016-03-27 04:52
As @bd4e5f6 is merged I'm closing this issue, 

Thanks!

~Timothy

**Closed by timothycrosley** 2016-03-27 04:52 UTC
Labels: bug

**Comment by hobarrera** [comment] 2016-03-27 06:03
Thanks! I'll be eagerly waiting for the next release to trim down workarounds in my projects! 😄

**Comment by ppolewicz** [comment] 2016-03-27 07:56
@timothycrosley when will it be released on pip?

**Comment by timothycrosley** [comment] 2016-03-27 19:29
@ppolewicz, I'm going to target a release today, sometime next week at the latest. I apologize I did not get to this issue sooner. It's not an acceptable amount of delay IMO, I've been heads down finishing the 2.0.0 release of hug: https://github.com/timothycrosley/hug and had trouble juggling the two, I'll be looking for a joint maintainer for this project to keep this from happening in the future. 

Thanks!

~Timothy
