### ISSUE TITLE
known_standard_library should add to the known set rather than replacing it

### ISSUE THREAD

**Issue by andersk** [timothycrosley/isort#1238] opened 2020-06-25 02:10 UTC
In `develop`, you can’t add modules to `known_standard_library` without replacing the entire set. This is a regression from isort 4.

For example, with `known_standard_library = zoneinfo` (new in Python 3.9, which I’m not running), isort 4 gives

```python
import os
import re
import sys
import zoneinfo

import numpy
import requests
import six
```

but `develop` gives

```python
import zoneinfo

import numpy
import os
import re
import requests
import six
import sys
```

**Comment by timothycrosley** [comment] 2020-06-25 05:09
@andersk It is not a regression, but an intentional change. Most other tools don't allow merging settings in that way, and isort has historically had several issues reported due to unexpected merging in this way. Isort should automatically detect zoneinfo as stdlib, without needing to add it to the list. Is there any example where a user should need to add to the stdlib list, without isort itself knowing that it is stdlib now that the list is meant to be extensive?

**Comment by andersk** [comment] 2020-06-25 06:13
Some actual examples from zulip/zulip are `posixpath` (which I see you just added) and `sre_constants`. Also, if new modules are added to the standard library in the future, users may not want to wait for an isort release to start using them—especially given that there hasn’t been an isort release for a year—and will want a way to configure isort for them without re-typing the entire list of existing standard library modules.

**Comment by timothycrosley** [comment] 2020-06-26 07:07
@andersk Thanks! These are all great points! I think, what I could do that would allow both models of thinking to work is to add an extra_stdlibs configuration option - or similar. That way both options could be immutable while allowing adding individual libraries. In the meantime I've also added both of the stdlibs you mentioned to the generated stdlibs.

**Comment by timothycrosley** [comment] 2020-06-29 05:40
This has been fixed in develop with an `--extra-builtin` command line flag or `extra_standard_library` config option.

**Closed by timothycrosley** 2020-06-29 05:40 UTC
Labels: question
