### ISSUE TITLE
inconsistent results from isort when used in CI on travis

### ISSUE THREAD

**Issue by samuelcolvin** [timothycrosley/isort#457] opened 2016-08-07 12:33 UTC
https://travis-ci.org/samuelcolvin/arq/builds/150409550

I'm trying to use isort in CI to make sure import orders are always correct, however I'm getting different results locally and on travis.

In [/arq/testing.py](https://github.com/samuelcolvin/arq/blob/6f0555f6808aa6bde20e874646714e3fc5f4c636/arq/testing.py#L8-L9) isort on travis says there should be a blank link (see build report above), locally it says it's fine.

Both setups are running isort 4.2.5 with python 3.5.

The only difference I can find is that the local version of python is 3.5.0, while on travis it's 3.5.2.

**Comment by kaedroho** [comment] 2017-05-26 11:33
Just been debugging this as I've hit this issue on a project I'm working on. It seems to be an issue with the way dependencies are installed. If dependencies are being installed with ``distutils`` (aka ``python setup.py install``, some dependencies such as ``Pillow`` and ``BeautifulSoup`` get detected as "first party" by ``isort``. This is probably because these dependencies use aliases (PIL = Pillow, bs4 = BeautifulSoup) which are handled differently by ``distutils`` so ``isort`` can't see them in your virtual environment and it assumes they're first party.

A workaround is to run ``pip install -e.`` instead of ``python setup.py install``. If you have caching enabled, don't forget to clear it!

**Comment by kaedroho** [comment] 2017-05-26 11:36
@samuelcolvin The blank line you're getting indicates one of the imports are being detected as a different category to the other. Did you install all dependencies the same way locally as you did on TravisCI?

**Comment by kaedroho** [comment] 2017-05-26 11:48
You can also workaround this by explicitly stating which dependencies are first/third party by using the ``known_first_party`` and ``known_third_party`` settings.

**Comment by timothycrosley** [comment] 2017-05-30 06:42
@celebdor's suggestions are on point, closing this issue for now, as I haven't been able to directly reproduce

Thanks!

~Timothy

**Closed by timothycrosley** 2017-05-30 06:42 UTC
Labels: bug

**Comment by samuelcolvin** [comment] 2017-05-30 11:33
Sorry not to close this issue sooner, pretty sure the problem was installing the library via `pip install -e ...` which made it appear "1st party", then installing it normally on travis.

**Comment by timothycrosley** [comment] 2017-05-30 17:26
@samuelcolvin No worries! Glad your issue was resolved :)

**Comment by auvipy** [comment] 2018-09-26 14:47
facing it on celery project as well. any suggestions?
