### ISSUE TITLE
Isort breaks on multiple imports with `import as`

### ISSUE THREAD

**Issue by thisfred** [timothycrosley/isort#804] opened 2019-01-19 22:02 UTC
Isort breaks  code of the form:

```python
from foo import bar as renamed_bar

from foo import bar

renamed_bar()
bar()
 ```

Running Isort 4.3.4 without any configuration settings, turns this into:

```python
from foo import bar as renamed_bar

renamed_bar()
bar()
```

which is syntactically invalid.

The original code is admittedly weird, but it's valid Python, and occurs in the wild in things like alembic migrations.

**Comment by dset0x** [comment] 2019-02-21 10:39
Duplicate of #606 ?

**Closed** 2019-03-11 00:54 UTC
Labels: duplicate
