### ISSUE TITLE
Comment lines removed when file is sorted

### ISSUE THREAD

**Issue by edmorley** [timothycrosley/isort#691] opened 2018-04-08 22:49 UTC
When isort is run on this file (via `isort --dont-skip '__init__.py' treeherder/__init__.py`), it unexpectedly removes the two comment lines highlighted here:
https://github.com/mozilla/treeherder/blob/addd73c8631ee2c005a0139bf0a88fabe3c6a24b/treeherder/__init__.py#L2-L3

Resulting in:
```python
import os

from .celery import app as celery_app  # noqa

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))


def path(*subdirectories):
    return os.path.join(PROJECT_DIR, *subdirectories)
```

This is using isort 4.3.4 under Python 2.7.14.

**Comment by mozbhearsum** [comment] 2019-04-09 20:10
Possible dupe of #787?

**Comment by timothycrosley** [comment] 2019-04-10 04:23
@mozbhearsum Thanks for bringing this back to the surface! I think it's likely to be a dupe of that ticket, either way, I've added a test case that verifies that it no longer is an issue with the latest release of isort.

Thanks!

~Timothy

**Closed by timothycrosley** 2019-04-10 04:23 UTC
Labels: bug
